USE MASTER
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = N'445_YuGiOh')
  BEGIN
 	-- Close connections to the DWPubsSales database
	ALTER DATABASE [445_YuGiOh] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
	DROP DATABASE [445_YuGiOh]
  END
GO

CREATE DATABASE [445_YuGiOh]
GO

USE [445_YuGiOh]
GO

CREATE TABLE [dbo].[TYPE] (
    [TypeID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL
    , [TypeName] varchar(75) NOT NULL
    , [TypeDesc] varchar(75) NULL
)

CREATE TABLE [dbo].[SUBTYPE] (
    [SubTypeID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL
    , [SubTypeName] varchar(75) NOT NULL
    , [SubTypeDesc] varchar(75) NULL
)

-- Create Rarity
CREATE TABLE [dbo].[Rarity] (
[RarityID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL
, [RarityName] VARCHAR(75)  NOT NULL
, [RarityDesc] VARCHAR(255)  NULL
)
GO

--Create Attribute
CREATE TABLE [dbo].[Attribute] (
[AttributeID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL
, [AttributeName] VARCHAR(75)  NOT NULL
, [AttributeDesc] VARCHAR(255)  NULL
)
GO

-- Create Card
    CREATE TABLE [dbo].[CARD] (
    [CardID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL
    , [CardName] VARCHAR(75)  NOT NULL
    , [CardNum] VARCHAR(75) NOT NULL
    , [CardText] VARCHAR(225) NOT NULL
    , [Level] INT NULL
    , [ATK] INT NULL
    , [DEF] INT NULL
    , [TypeID] INT FOREIGN KEY REFERENCES [TYPE](TypeID) NOT NULL
    , [RarityID] INT FOREIGN KEY REFERENCES [RARITY](RarityID) NOT NULL
    , [AttributeID] INT FOREIGN KEY REFERENCES [ATTRIBUTE](AttributeID) NULL
    , [SubTypeID] INT FOREIGN KEY REFERENCES [SUBTYPE](SubTypeID) NULL
)
GO

-- CREATE STATE
CREATE TABLE [dbo].[STATE] (
    [StateID] INT PRIMARY KEY IDENTITY(1,1)  NOT NULL
    , [StateName] VARCHAR(75)  NOT NULL
    )
GO

-- Create CITY
CREATE TABLE [dbo].[CITY] (
    [CityID] INT PRIMARY KEY IDENTITY(1,1)   NOT NULL
    , [StateID] INT CONSTRAINT [STATE_CITY_FK] FOREIGN KEY REFERENCES [STATE](StateID) NOT NULL
    , [CityName] VARCHAR(75)  NOT NULL
)
GO

-- Create ADDRESS
CREATE TABLE [dbo].[ADDRESS] (
    [AddressID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL
    , [CityID] INT CONSTRAINT [CITY_ADDRESS_FK] FOREIGN KEY REFERENCES [CITY](CityID) NOT NULL
    , [StreetAddress] VARCHAR(255)  NOT NULL
    , [PostCode] char(3) NULL
)
GO

-- Create USER_TYPE
CREATE TABLE [dbo].[USER_TYPE] (
    [UserTypeID] INT PRIMARY KEY IDENTITY(1,1)   NOT NULL
    , [UserTypeName] VARCHAR(75)  NOT NULL
    , [UserTypeDesc] VARCHAR(255)  NULL
)
GO

-- Create USER
CREATE TABLE [dbo].[USER] (
    [UserID] INT PRIMARY KEY IDENTITY(1,1)  NOT NULL
    , [UserTypeID] INT CONSTRAINT [USER_TYPE_USER_FK] FOREIGN KEY REFERENCES [USER_TYPE](UserTypeID) NOT NULL
    , [AddressID] INT CONSTRAINT [ADDRESS_USER_FK] FOREIGN KEY REFERENCES [ADDRESS](AddressID) NOT NULL
    , [FirstName] VARCHAR(75)  NOT NULL
    , [LastName] VARCHAR(75)  NOT NULL
    , [Email] VARCHAR(255)  NOT NULL
    , [DOB] DATETIME  NOT NULL
)
GO

-- Create CONDITION
CREATE TABLE [dbo].[CONDITION] (
[CardConditionID] INT PRIMARY KEY IDENTITY(1,1)  NOT NULL
, [CardConditionName] VARCHAR(75)  NOT NULL
, [CardConditionDesc] VARCHAR(255)  NULL
)
GO

-- Create USER_CARD
CREATE TABLE [dbo].[USER_CARD] (
[UserCardID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL
, [UserID] INT CONSTRAINT [USER_USER_CARD_FK] FOREIGN KEY REFERENCES [USER](UserID) NOT NULL
, [CardID] INT CONSTRAINT [CARD_USER_CARD_FK] FOREIGN KEY REFERENCES [CARD](CardID) NOT NULL
, [CardConditionID] INT CONSTRAINT [CONDITION_USER_CARD_FK] FOREIGN KEY REFERENCES [CONDITION](CardConditionID) NOT NULL
, [BeginDate] DATETIME  NOT NULL
, [EndDate] DATETIME  NULL
)
GO

-- Create EVENT_TYPE
CREATE TABLE [dbo].[EVENT_TYPE] (
    [EventTypeID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL
    , [EventTypeName] VARCHAR(75)  NOT NULL
    , [EventTypeDesc] VARCHAR(255)  NULL
    )
GO

-- Create EVENT
CREATE TABLE [dbo].[EVENT] (
    [EventID] INT PRIMARY KEY IDENTITY(1,1) NOT NULL
    , [UserCardID] INT CONSTRAINT [USER_CARD_EVENT_FK] FOREIGN KEY REFERENCES USER_CARD(UserCardID) NOT NULL
    , [EventTypeID] INT CONSTRAINT [EVENT_TYPE_EVENT_FK] FOREIGN KEY REFERENCES EVENT_TYPE(EventTypeID) NOT NULL
    , [Date] DATETIME  NOT NULL
    , [Price] DECIMAL(17,2) NOT NULL
)
GO